export const tableData = [
	{
		id: 1,
		name: 'Leanne Graham',
		username: 'Bret',
		email: 'Sienre@april.biz',
		address: 'Gwenbough',
		phone: '1-770-736-8031 x56-422',
		website: 'hildegaer.org',
		company: 'Rpmaguere-Crona',
	},
	{
		id: 2,
		name: 'Ervin Howell',
		username: 'Antonnette',
		email: 'Shanna@malissa.tv',
		address: 'Wisokyburgh',
		phone: '010-692-6593 x09125',
		website: 'anastasia.net',
		company: 'Deckow-Crest',
	},
	{
		id: 3,
		name: 'Clementine Bauch',
		username: 'Samantha',
		email: 'Nathan@yesenis.net',
		address: 'McKenZiehaven',
		phone: '1-463-123-4447',
		website: 'ramiro.info',
		company: 'Romaguera-Jacobson',
	},
	{
		id: 4,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
	{
		id: 5,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
	{
		id: 6,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
	{
		id: 7,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
	{
		id: 8,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
	{
		id: 9,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
	{
		id: 10,
		name: 'Patricia Lebsack',
		username: 'Kariabnne',
		email: 'Julianne.OConner@kory.org',
		address: 'South Elvis',
		phone: '493-170-9623 x156',
		website: 'kale.biz',
		company: 'Robel-Corkery',
	},
];
